---
name: Win32-Crypt
version: 0.00_004
author: ~
abstract: ~
license: perl
requires:
  Win32::API::Interface: 0.01
  constant: 1.05
provides:
  Win32::Crypt::API:
    file: lib/Win32/Crypt/API.pm
    version: 0.00_004
generated_by: Module::Build version 0.2611
